### ISSUE TITLE
Error while running sample application

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/TrackableEntities.Core#9]
When trying to load a particular order for a customer getting the following error.

`System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NetCoreSample.ConsoleClient.Program.GetCustomerOrders(HttpClient client, String customerId, MediaTypeFormatter formatter) in C:\Users\Noufal\Downloads\TrackableEntities.Core.Sample-master\NetCoreSample.ConsoleClient\Program.cs:line 146
   at NetCoreSample.ConsoleClient.Program.Main(String[] args) in C:\Users\Noufal\Downloads\TrackableEntities.Core.Sample-master\NetCoreSample.ConsoleClient\Program.cs:line 45

Inner Exception 1:
JsonReaderException: The reader's MaxDepth of 256 has been exceeded. Path '$values[0].customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[2].order.customer.orders.$values[1].orderDetails.$values[2].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[2].order.customer.orders.$values[0].orderDetails.$values[1].product.orderDetails.$values[1].order.customer.orders.$values[1].orderDetails.$values[1].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[4].order.customer.orders.$values[1].orderDetails.$values[2].product.orderDetails.$values[0].order.orderDetails.$values[1].product.orderDetails.$values[2].order.customer.orders.$values[1].orderDetails.$values', line 1, position 26526.
`

**Comment by tonysneed** [comment]
You need to configure the Json.Net serializer to handle cyclical references. See the sample app for an example.

**Comment by noufionline** [comment]
In your sample the following code creating the issue 
`string request = $"api/Order?customerId=" + customerId;`

When tried with 
`string request = $"api/Order/{customerId}";` 
Its working fine. Any thoughts on this?

**Comment by tonysneed** [comment]
Yes, you'll get the serialization exception only if your object graph has cycles.  In other words, if you have, for example, a Product with a Category property that has a Products property with the Product you are retrieving.  If you look at the `Startup` class in the [sample](https://github.com/TrackableEntities/TrackableEntities.Core.Sample) project, you'll see this [line](https://github.com/TrackableEntities/TrackableEntities.Core.Sample/blob/master/NetCoreSample.Web/Startup.cs#L20) of code:

```csharp
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
        .AddJsonOptions(options =>
            options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.All);
        }
```
That will instruct the JSON.Net serializer to handle cyclical references, so you won't get the error.  However, you must also configure the serializer on the client.  To see how that's done, take a look at the [GetFormatter](https://github.com/TrackableEntities/TrackableEntities.Core.Sample/blob/master/NetCoreSample.ConsoleClient/Program.cs#L123) method.

```csharp
private static void GetFormatter(out MediaTypeFormatter formatter, out string acceptHeader)
{
    var jsonFormatter = new JsonMediaTypeFormatter();
    jsonFormatter.JsonPreserveReferences();
    formatter = jsonFormatter;
    acceptHeader = "application/json";
}
```

Let me know if this makes sense.  Cheers.

**Comment by noufionline** [comment]
Thanks, Tony,

Yes, I got your point. I haven't changed a single line of code in your sample application. Even if I try to run the sample as is it gives this error. That means the above-mentioned options doesn't have any effect when we are calling the endpoint using a query string.

So `string request = $"api/Order?customerId=" + customerId;` this method must be avoided in favour of `string request = $"api/Order/{customerId}";`

Awaiting your reply

**Comment by tonysneed** [comment]
I'm surprised the first route even works, because the route on the controller action specifies that the parameter needs to come from the URI and the provided template specifies the path.  However, I am not getting an error when I execute this in a browser: `http://localhost:64139/api/order?customerId=ALFKI`.

Likewise, when I execute the client, I don't get an error, even though the request uses the query parameter:  `request = "api/Order?customerId=" + customerId;`

Either way, the error you're getting has nothing to do with the format of the request.  Rather it is a serialization error.  So I'm not sure how to counsel you because I'm unable to reproduce your error on my end.

**Comment by tonysneed** [comment]
We can re-open if more info becomes available.

**Comment by DavidRogersDev** [comment]
I encountered this error as well when running through the sample.
I was able to clear the way by upping the MaxDepth property on the jsonFormatter.

So, under the line `jsonFormatter.JsonPreserveReferences();`, I added `jsonFormatter.MaxDepth = 1000`

Hope this helps!
